- name: Create a directories for disks
  ansible.builtin.file:
    path: /mnt/{{ item }}
    state: directory
    mode: '0755'
  loop: "{{ labels }}"

- name: Mount up device by label
  ansible.posix.mount:
    path: /mnt/{{ item }}
    src: LABEL={{ item }}
    fstype: ext4
    state: present
  loop: "{{ labels }}"

- name: Create a directory for share
  ansible.builtin.file:
    path: /mnt/media/shara
    state: directory
    mode: '0755'

- name: Create a directory for docker volumes
  ansible.builtin.file:
    path: /mnt/docker/data_apps
    state: directory
    mode: '0755'

- name: Create daemon.json file
  ansible.builtin.copy:
    content: '{"data-root": "/mnt/docker/data_docker"}'
    dest: /etc/docker/daemon.json
    follow: true
    owner: root
    group: root
    mode: '0644'

- name: Restart Docker Daemon
  ansible.builtin.service:
    name: docker
    state: restarted
